#ifndef _GEOMETRY_GEOMETRY_GLOBAL_H_
#define _GEOMETRY_GEOMETRY_GLOBAL_H_

#include "CsGlobal.h"

#define CS_GEOMETRY_HAS_Z

#ifdef CS_GEOMETRY_HAS_Z
#	define CS_COORDINATE_SIZE	3
#	define CS_ENVELOPE_SIZE		6
#	define CS_COORDINATE_X_POS	0
#	define CS_COORDINATE_Y_POS	1
#	define CS_COORDINATE_Z_POS	2
#else // !CS_GEOMETRY_HAS_Z
#	define CS_COORDINATE_SIZE	2
#	define CS_ENVELOPE_SIZE		4
#	define CS_COORDINATE_X_POS	0
#	define CS_COORDINATE_Y_POS	1
#endif // CS_GEOMETRY_HAS_Z

// 维度 * 4
enum CS_GEOMETRY_DIMENSION
{
	GEOMETRY_DIMENSION_0 = 0,	/**< 零维 */
	GEOMETRY_DIMENSION_1 = 1,	/**< 一维 */
	GEOMETRY_DIMENSION_2 = 2,	/**< 二维 */
	GEOMETRY_DIMENSION_3 = 3,	/**< 三维 */
};

// 坐标类型 * 2
enum CS_GEOMETRY_COORDINATE
{
	GEOMETRY_COORDINATE_PLANE	= 0,	/**< 平面 */
	GEOMETRY_COORDINATE_SPHERE	= 1,	/**< 球面 */
};

// 几何类型 * 32
enum CS_GEOMETRY_TYPE
{
	GEOMETRY_TYPE_NULL = 0,
	GEOMETRY_TYPE_POINT = 1,
	GEOMETRY_TYPE_LINE = 2,
	GEOMETRY_TYPE_POLYLINE = 3,
	GEOMETRY_TYPE_POLYLGON = 4,
	GEOMETRY_TYPE_TRIANGLE = 5,
	GEOMETRY_TYPE_QUADRANGLE = 6,
	GEOMETRY_TYPE_MULTI_POINT = 7,
	GEOMETRY_TYPE_MULTI_LINE = 8,
	GEOMETRY_TYPE_MULTI_POLYLINE = 9,
	GEOMETRY_TYPE_MULTI_POLYLGON = 10,

	// Polyhedron，多面体
	// Tetrahedron，四面体
	// Hexahedron，六面体
};



#endif // _GEOMETRY_GEOMETRY_GLOBAL_H_