#ifndef _GEOMETRY_GEOMETRY_CORE_H_
#define _GEOMETRY_GEOMETRY_CORE_H_

#define CS_GEOMETRY_COORDINATE_HAS_Z

#ifdef CS_GEOMETRY_COORDINATE_HAS_Z
#	define CS_COORDINATE_SIZE	3
#	define CS_ENVELOPE_SIZE		6
#	define CS_COORDINATE_X_POS	0
#	define CS_COORDINATE_Y_POS	1
#	define CS_COORDINATE_Z_POS	2
#else // !CS_GEOMETRY_COORDINATE_HAS_Z
#	define CS_COORDINATE_SIZE	2
#	define CS_ENVELOPE_SIZE		4
#	define CS_COORDINATE_X_POS	0
#	define CS_COORDINATE_Y_POS	1
#endif // CS_GEOMETRY_COORDINATE_HAS_Z

#ifdef CS_GEOMETRY_COORDINATE_HAS_Z

#else // !CS_GEOMETRY_COORDINATE_HAS_Z

#endif // CS_GEOMETRY_COORDINATE_HAS_Z

#endif // _GEOMETRY_GEOMETRY_CORE_H_