#ifndef _CORE_CLASS_CODE_H_
#define _CORE_CLASS_CODE_H_

enum CS_CORE_CLASSCODE
{
	CORE_CLASSCODE_OBJECT = 0,					// Object

	CORE_CLASSCODE_PACKAGE,						// Package
	CORE_CLASSCODE_NUMBER,						// Number
	CORE_CLASSCODE_BYTE,						// Byte
	CORE_CLASSCODE_BOOLEAN,						// Boolean
	CORE_CLASSCODE_CHARACTER,					// Character
	CORE_CLASSCODE_SIGNED_CHARACTER,			// SignedCharacter
	CORE_CLASSCODE_UNSIGNED_CHARACTER,			// UnsignedCharacter
	CORE_CLASSCODE_WIND_CHARACTER,				// WindCharacter
	CORE_CLASSCODE_SMALL_INTEGER,				// SmallInteger
	CORE_CLASSCODE_UNSIGNED_SMALL_INTEGER,		// UnsignedSmallInteger
	CORE_CLASSCODE_SHORT_INTEGER,				// ShortInteger
	CORE_CLASSCODE_UNSIGNED_SHORT_INTEGER,		// UnsignedShortInteger
	CORE_CLASSCODE_INTEGER,						// Integer
	CORE_CLASSCODE_UNSIGNED_INTEGER,			// UnsignedInteger
	CORE_CLASSCODE_LONG_INTEGER,				// LongInteger
	CORE_CLASSCODE_UNSIGNED_LONG_INTEGER,		// UnsignedLongInteger
	CORE_CLASSCODE_LONG_LONG_INTEGER,			// LongLongInteger
	CORE_CLASSCODE_UNSIGNED_LONG_LONG_INTEGER,	// UnsignedLongLongInteger
	CORE_CLASSCODE_SINGLE_FLOAT,				// SingleFloat
	CORE_CLASSCODE_DOUBLE_FLOAT,				// DoubleFloat
	CORE_CLASSCODE_LONG_DOUBLE_FLOAT,			// LongDoubleFloat
	


	CORE_CLASSCODE_ARRAY,						// Array
	CORE_CLASSCODE_ARRAY_STACK,					// ArrayStack
	CORE_CLASSCODE_AUTO_LOCK,					// AutoLock
	CORE_CLASSCODE_BINARY_SORT_TREE,			// Binary Sort Tree
	CORE_CLASSCODE_BINARY_TREE,					// Binary Tree
	

	CORE_CLASSCODE_STRING,			// String
	CORE_CLASSCODE_THREAD,			// Thread
	CORE_CLASSCODE_MUTEX,			// Mutex
	CORE_CLASSCODE_CRITICAL_SECTION,	// CriticalSection

	CORE_CLASSCODE_SEMAPHORE,		// Semaphore
	CORE_CLASSCODE_SOCKET_ADDRESS,		// SockAddress
	CORE_CLASSCODE_SOCKET,			// Socket
	CORE_CLASSCODE_TCPSOCKET,		// TcpSocket
	CORE_CLASSCODE_UDPSOCKET,		// UdpSocket
	CORE_CLASSCODE_VECTOR,			// Vector
	CORE_CLASSCODE_LIST,			// List
	CORE_CLASSCODE_MAP,				// Map
	CORE_CLASSCODE_TABLE,			// Table
	CORE_CLASSCODE_FILE,			// File

	CORE_CLASSCODE_DATE,			// Date

	CORE_CLASSCODE_RBTREE_NODE,		// RBTreeNode

	CORE_CLASSCODE_GEOMETRY,
};

#endif // _CORE_CLASS_CODE_H_