#ifndef _CSCORE_CSCOREGLOBAL_H_
#define _CSCORE_CSCOREGLOBAL_H_

#include "CsGlobal.h"

#  if defined (CS_CORE_BUILD_DLL)
#    define CsCore_Export CS_DECL_EXPORT
#  else 
#    define CsCore_Export CS_DECL_IMPORT
#  endif  

enum EM_CORE_CLASSCODE
{
	CORE_CLASSCODE_OBJECT = 0,		// Object
	CORE_CLASSCODE_BYTE,			// Byte
	CORE_CLASSCODE_CHARACTER,		// Character
	CORE_CLASSCODE_BOOLEAN,			// Boolean
	CORE_CLASSCODE_INT8,			// Int8
	CORE_CLASSCODE_INT16,			// Int16
	CORE_CLASSCODE_INT32,			// Int32
	CORE_CLASSCODE_INT64,			// Int64
	CORE_CLASSCODE_FLOAT,			// Float
	CORE_CLASSCODE_DOUBLE,			// Double
	CORE_CLASSCODE_DECIMAL,			// Decimal
	CORE_CLASSCODE_STRING,			// String
	CORE_CLASSCODE_THREAD,			// Thread
	CORE_CLASSCODE_MUTEX,			// Mutex
	CORE_CLASSCODE_AUTO_LOCK,		// AutoLock
	CORE_CLASSCODE_SEMAPHORE,		// Semaphore
	CORE_CLASSCODE_SOCKET_ADDRESS,	// SockAddress
	CORE_CLASSCODE_SOCKET,			// Socket
	CORE_CLASSCODE_TCPSOCKET,		// TcpSocket
	CORE_CLASSCODE_UDPSOCKET,		// UdpSocket
	CORE_CLASSCODE_VECTOR,			// Vector
	CORE_CLASSCODE_LIST,			// List
	CORE_CLASSCODE_MAP,				// Map
	CORE_CLASSCODE_TABLE,			// Table
	CORE_CLASSCODE_FILE,			// File

	CORE_CLASSCODE_DATE,			// Date
};

#endif // _CSCORE_CSCOREGLOBAL_H_